image: docker:latest
services:
  - docker:dind

variables:

stages:
  - build

before_script:
  - docker login -u yahel2410 -p $PASSWORD $CI_REGISTRY
  - docker login -u yahel2410 -p $PASSWORD https://index.docker.io/v1/

build:
  stage: build
  script:
    - docker build --build-arg VERTICA_VERSION=$vertica_version
                   -t $CI_REGISTRY_IMAGE:$vertica_version
                   -t yahel2410/vertica-client-docker:$vertica_version .
    - docker push $CI_REGISTRY_IMAGE:$vertica_version
    - docker push yahel2410/vertica-client-docker:$vertica_version
  only:
    - web
  tags:
    - docker



